project:
  type: website
  output-dir: docs

website:
  title: "Home"
  site-url: "https://jsnsoto04.github.io/MATH-437/"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Jason Soto
    right:
      - text: Home
        href: index.qmd
      - href: final_project.qmd 
        text: Final Project
    tools:
      - icon: github
        href: https://github.com/jsnsoto04
      - icon: linkedin
        href: https://www.linkedin.com/in/jason-soto-6562963aa/
      
format:
  html:
    code-block-bg: "#171717"
    code-block-border-left: "#817E7E"
    fontcolor: "white"
    linkcolor: "#289EC6"
    backgroundcolor: "#121212"
    monobackgroundcolor: "#171717"
    mainfont: "Avnir light"
    monofont: "monospace"
    max-width: ""
    fontsize: ""
    linestretch: ""
    theme: darkly
